@url =  http://localhost:7777

###

POST http://localhost:7777/api/user/register
Content-Type: application/json


{
    "loginInfo": 
    {
        "email":"ronnykorneli@ma.com",
        "password":"horhhih0000!!J", 
        "role": "admin"
    }
}

###

POST http://localhost:7777/api/user/login
Content-Type: application/json


{
        "email":"Fred",
        "password":"horse"
}

###

PATCH http://localhost:7777/api/user/62aafc1ce396b03c82def4ed
Content-Type: application/json

{
    "loginInfo":{
        "email":"gigno@Ginjo.de"
    }
}

