@url =  http://localhost:7777

###

POST http://localhost:7777/api/user/register
Content-Type: application/json


{
    "loginInfo":{

        "email":"Fred",
        "password":"horse"

        
    }
}

###

POST http://localhost:7777/api/user/login
Content-Type: application/json


{
        "email":"Fred",
        "password":"horse"
}
